name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run build
        run: go build .

      - name: Run audit
        run: make audit

      - name: Run testing
        run: cd tests && go test -v ./...